### ISSUE TITLE
When editing a snippet, a '\n' space is added automatically

### ISSUE THREAD

**Issue by EsJuanSalomon** [inu1255/vscode-easy-snippet#10]
When editing a snippet, a '\n' space is added automatically before the code [snippet body], so each time it is edited, more line breaks are added and when the snippet is used these spaces are also inserted in the user code.  

Version VSC : 1.39.2 
easy-snippet versión: 0.1.7

**Comment by lastobelus** [comment]
what language is your snippet?

I don't have this problem, but was having a newline always added to the _bottom_ of [elixir] snippets. Turns out it was the formatter for Elixir adding it -- easy-snippet sets the language of the temporary file it uses for editing to the language group the snippet is in so that you get syntax highlighting.

**Comment by anthonyrivas** [comment]
This is true for Typescript. 

In js there is an eslint-disable added to the newline in snippet2text.  The same needs to be true for Typescript to avoid this happening. I will make a PR for this fix.

**Comment by inu1255** [comment]
Sorry to reply so late, but this bug is already fixed.
